name: Dependency Update

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Update backend dependencies
      working-directory: ./backend
      run: |
        npm update
        npm audit fix --audit-level moderate
        
    - name: Update frontend dependencies
      working-directory: ./frontend
      run: |
        npm update
        npm audit fix --audit-level moderate

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: '🔄 Weekly Dependency Updates'
        body: |
          ## Dependency Updates
          
          This PR contains automated dependency updates for both backend and frontend.
          
          ### Changes
          - Updated npm packages to latest versions
          - Applied security fixes for moderate vulnerabilities
          
          ### Testing
          Please run the full test suite before merging.
        branch: dependency-updates
        delete-branch: true